apiVersion: apps/v1
kind: Deployment
metadata:
  name: httpd-deployment
  labels:
    app: httpd
spec:
  replicas: 3
  selector:
    matchLabels:
      app: httpd
  template:
    metadata:
      labels:
        app: httpd
    spec:
      containers:
      - name: httpd
        image: httpd:latest
        ports:
        - containerPort: 80

example 2:-

[ centos@ip-172-31-5-129 ~/DockerK8sPOC ]$ cat 01-deploy-http.yml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: httpd-deployment
  labels:
    app: httpd
spec:
  replicas: 3
  selector:
    matchLabels:
      app: httpd
  template:
    metadata:
      labels:
        app: httpd
    spec:
      containers:
      - name: httpd
        image: httpd:latest
        ports:
        - containerPort: 80

35.175.122.133 | 172.31.5.129 | t3.medium | https://github.com/kalindalapreethiyadav/DockerK8sPOC.git
[ centos@ip-172-31-5-129 ~/DockerK8sPOC ]$ kubectl apply -f 01-deploy-http.yml
deployment.apps/httpd-deployment created

35.175.122.133 | 172.31.5.129 | t3.medium | https://github.com/kalindalapreethiyadav/DockerK8sPOC.git
[ centos@ip-172-31-5-129 ~/DockerK8sPOC ]$ kubectl get deploy
NAME               READY   UP-TO-DATE   AVAILABLE   AGE
httpd-deployment   3/3     3            3           10s
nginx-deployment   3/3     3            3           7m46s

35.175.122.133 | 172.31.5.129 | t3.medium | https://github.com/kalindalapreethiyadav/DockerK8sPOC.git
[ centos@ip-172-31-5-129 ~/DockerK8sPOC ]$ kubectl get pods
NAME                                READY   STATUS                       RESTARTS   AGE
httpd-deployment-d6598d6c5-8sb9v    1/1     Running                      0          20s
httpd-deployment-d6598d6c5-hz8b6    1/1     Running                      0          20s
httpd-deployment-d6598d6c5-j6wjm    1/1     Running                      0          20s
mongodb                             0/1     ImagePullBackOff             0          24h
nginx-deployment-85996f8dbd-svrjv   1/1     Running                      0          7m56s
nginx-deployment-85996f8dbd-w7br8   1/1     Running                      0          7m56s
nginx-deployment-85996f8dbd-zshmq   1/1     Running                      0          7m56s
tomcat                              0/1     CreateContainerConfigError   0          25h

#scale the replicas in the deployment:-
-------------------------'
35.175.122.133 | 172.31.5.129 | t3.medium | https://github.com/kalindalapreethiyadav/DockerK8sPOC.git
[ centos@ip-172-31-5-129 ~/DockerK8sPOC ]$ kubectl get pods --watch
NAME                                READY   STATUS                       RESTARTS   AGE
httpd-deployment-d6598d6c5-8sb9v    1/1     Running                      0          5m6s
httpd-deployment-d6598d6c5-hz8b6    1/1     Running                      0          5m6s
httpd-deployment-d6598d6c5-j6wjm    1/1     Running                      0          5m6s
mongodb                             0/1     ImagePullBackOff             0          24h
nginx-deployment-85996f8dbd-svrjv   1/1     Running                      0          12m
nginx-deployment-85996f8dbd-w7br8   1/1     Running                      0          12m
nginx-deployment-85996f8dbd-zshmq   1/1     Running                      0          12m
tomcat                              0/1     CreateContainerConfigError   0          25h
^C
35.175.122.133 | 172.31.5.129 | t3.medium | https://github.com/kalindalapreethiyadav/DockerK8sPOC.git
[ centos@ip-172-31-5-129 ~/DockerK8sPOC ]$ kubectl scale deploy httpd-deployment --replicas=2
deployment.apps/httpd-deployment scaled

35.175.122.133 | 172.31.5.129 | t3.medium | https://github.com/kalindalapreethiyadav/DockerK8sPOC.git
[ centos@ip-172-31-5-129 ~/DockerK8sPOC ]$ kubectl get pods --watch
NAME                                READY   STATUS                       RESTARTS   AGE
httpd-deployment-d6598d6c5-hz8b6    1/1     Running                      0          5m53s
httpd-deployment-d6598d6c5-j6wjm    1/1     Running                      0          5m53s
mongodb                             0/1     ImagePullBackOff             0          24h
nginx-deployment-85996f8dbd-svrjv   1/1     Running                      0          13m
nginx-deployment-85996f8dbd-w7br8   1/1     Running                      0          13m
nginx-deployment-85996f8dbd-zshmq   1/1     Running                      0          13m
tomcat                              0/1     CreateContainerConfigError   0          25h

'^C
35.175.122.133 | 172.31.5.129 | t3.medium | https://github.com/kalindalapreethiyadav/DockerK8sPOC.git
[ centos@ip-172-31-5-129 ~/DockerK8sPOC ]$ kubectl scale deploy nginx-deployment --replicas=2
deployment.apps/nginx-deployment scaled

35.175.122.133 | 172.31.5.129 | t3.medium | https://github.com/kalindalapreethiyadav/DockerK8sPOC.git
[ centos@ip-172-31-5-129 ~/DockerK8sPOC ]$ kubectl get pods
NAME                                READY   STATUS                       RESTARTS   AGE
httpd-deployment-d6598d6c5-hz8b6    1/1     Running                      0          9m30s
httpd-deployment-d6598d6c5-j6wjm    1/1     Running                      0          9m30s
mongodb                             0/1     ImagePullBackOff             0          24h
nginx-deployment-85996f8dbd-w7br8   1/1     Running                      0          17m
nginx-deployment-85996f8dbd-zshmq   1/1     Running                      0          17m
tomcat                              0/1     CreateContainerConfigError   0          25h

35.175.122.133 | 172.31.5.129 | t3.medium | https://github.com/kalindalapreethiyadav/DockerK8sPOC.git
[ centos@ip-172-31-5-129 ~/DockerK8sPOC ]$ kubectl get ns
NAME               STATUS   AGE
calico             Active   3d1h
calico-apiserver   Active   3d1h
calico-system      Active   3d1h
default            Active   3d1h
dev                Active   57m
kube-node-lease    Active   3d1h
kube-public        Active   3d1h
kube-system        Active   3d1h

35.175.122.133 | 172.31.5.129 | t3.medium | https://github.com/kalindalapreethiyadav/DockerK8sPOC.git
[ centos@ip-172-31-5-129 ~/DockerK8sPOC ]$ kubectl get deploy
NAME               READY   UP-TO-DATE   AVAILABLE   AGE
httpd-deployment   2/2     2            2           10m
nginx-deployment   2/2     2            2           17m

35.175.122.133 | 172.31.5.129 | t3.medium | https://github.com/kalindalapreethiyadav/DockerK8sPOC.git
[ centos@ip-172-31-5-129 ~/DockerK8sPOC ]$ kubectl get replicaset
NAME                          DESIRED   CURRENT   READY   AGE
httpd-deployment-d6598d6c5    2         2         2       10m
nginx-deployment-85996f8dbd   2         2         2       17m

#hideen pods

35.175.122.133 | 172.31.5.129 | t3.medium | https://github.com/kalindalapreethiyadav/DockerK8sPOC.git
[ centos@ip-172-31-5-129 ~/DockerK8sPOC ]$ kubectl get pods -A
NAMESPACE          NAME                                                   READY   STATUS                       RESTARTS      AGE
calico-apiserver   calico-apiserver-76669b6c4-bq699                       1/1     Running                      2 (61m ago)   3d1h
calico-apiserver   calico-apiserver-76669b6c4-d59v7                       1/1     Running                      2 (61m ago)   3d1h
calico-system      calico-kube-controllers-8bd4657cc-qg9xj                1/1     Running                      2 (61m ago)   3d1h
calico-system      calico-node-7vbzc                                      1/1     Running                      2 (61m ago)   3d1h
calico-system      calico-typha-77ddfbf658-sjgj9                          1/1     Running                      3 (61m ago)   3d1h
calico-system      csi-node-driver-p5dj4                                  2/2     Running                      4 (61m ago)   3d1h
calico             tigera-operator-594d547464-5w82g                       1/1     Running                      3 (61m ago)   3d1h
default            httpd-deployment-d6598d6c5-hz8b6                       1/1     Running                      0             12m
default            httpd-deployment-d6598d6c5-j6wjm                       1/1     Running                      0             12m
default            mongodb                                                0/1     ImagePullBackOff             0             25h
default            nginx-deployment-85996f8dbd-w7br8                      1/1     Running                      0             20m
default            nginx-deployment-85996f8dbd-zshmq                      1/1     Running                      0             20m
default            tomcat                                                 0/1     CreateContainerConfigError   0             25h
dev                mongodb                                                0/1     ImagePullBackOff             0             58m
kube-system        coredns-787d4945fb-gh7k8                               1/1     Running                      2 (61m ago)   3d1h
kube-system        coredns-787d4945fb-p2bf2                               1/1     Running                      2 (61m ago)   3d1h
kube-system        dashboard-metrics-scraper-6c57f89c7c-gc79b             1/1     Running                      1 (61m ago)   3d1h
kube-system        etcd-ip-10-0-101-143.ec2.internal                      1/1     Running                      2 (61m ago)   3d1h
kube-system        external-dns-59d8d44b78-vkxzg                          1/1     Running                      1 (61m ago)   3d1h
kube-system        heapster-d56f79c9b-fzdsl                               1/1     Running                      2 (61m ago)   3d1h
kube-system        kube-apiserver-ip-10-0-101-143.ec2.internal            1/1     Running                      2 (61m ago)   3d1h
kube-system        kube-controller-manager-ip-10-0-101-143.ec2.internal   1/1     Running                      2 (61m ago)   3d1h
kube-system        kube-proxy-pdm4t                                       1/1     Running                      2 (61m ago)   3d1h
kube-system        kube-scheduler-ip-10-0-101-143.ec2.internal            1/1     Running                      2 (61m ago)   3d1h
kube-system        kubernetes-dashboard-d799f6d9c-lqx76                   1/1     Running                      2 (61m ago)   3d1h

