apiVersion: v1
kind: Pod
metadata:
  name: catalogue
  labels:
   tier: catalogue-nodejs  #matched with service tier name
spec:
  containers:
  - name: nodejs
    image: nodejs:latest

---

apiVersion: v1
kind: Service
metadata:
  name: catalogue-service
spec:
  type: LoadBalancer 
  selector:      
    tier: catalogue-nodejs  #matchs with pod tier label
  ports:
  - name: my-poo
    protocol: TCP
    port: 80
    targetPort: 80