
apiVersion: v1
kind: namespace
metadata:
  name: dev

---
apiVersion: v1
kind: Pod
metadata:
  name: nginx
  namespace: dev
spec:
  containers:
  - name: nginx
    image: nginx
    command: ["sleep","300"]
    envFrom:
      - configMapRef:
           name: config_tom