apiVersion: v1
kind: Pod
metadata:
  name: payment
  labels:
   tier: payment-mysql
spec:
  containers:
  - name: mysql
    image: mysql:latest

---

apiVersion: v1
kind: Service
metadata:
  name: payment-service
spec:
  selector:      
    tier: payment-mysql  #matchs with pod label
  ports:
  - name: my-poo
    protocol: TCP
    port: 80
    targetPort: 80

