apiVersion: v1
kind: Pod
metadata:
  name: python
spec:
  containers:
  - name: python
    image: python
    env:
      - name: projet_name
        value: projeck
      - name: url
        value: www.google.com