apiVersion: v1
kind: Pod
metadata:
  name: centos
spec:
  containers:
  - name: centos
    image: centos
    env:
      - name: projet_name
        value: projeck_centos
      - name: url
        value: www.google.com