apiVersion: v1
kind: Pod
metadata:
  name: nginx
spec:
  containers:
  - name: nginx
    image: nginx
    command: ["sleep","300"]
    envFrom:
      - configMapRef:
           name: config_tom

---

apiVersion: v1
kind: configMap
metadata:
  name: config_tom
data:
  project: projet_name
  pro_name: projeck_python
  name_url: url
  url_value: www.google.com