apiVersion: v1
kind: Pod
metadata:
  name: alpine
spec:
  containers:
  - name: alpnie
    image: alpine
    command: ["sleep","300"]
    envFrom:
      - configMapRef:
           name: config_tom