apiVersion: v1
kind: Pod
metadata:
  name: nginx
spec:
  containers:
  - name: nginx
    image: nginx
    command: ["sleep","300"]
    envFrom:
      - configMapRef:
           name: config_tom