apiVersion: v1
kind: Pod
metadata:
  name: tomcat
spec:
  containers:
  - name: tomcat
    image: tomcat:latest
    command: ["sleep","300"]
    envFrom:
      - configMapRef:
           name: 01-config